#!/usr/bin/env bash
#configures a new Ubuntu machine to respect certain requirments

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/html.index
sudo service nginx start
