#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it.
BACKUP_DATE=$(date +%d-%m-%y)
ARCHIVE_NAME=${BACKUP_DATE}.tar.gz

sudo mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$ARCHIVE_NAME" backup.sql
