#!/usr/bin/env bash
# Script to terminate the 4-to_infinity_and_beyond script

pid=

if [ -z "" ]; then
    echo "The process 4-to_infinity_and_beyond is not running."
else
    kill 
    echo "Terminated"
fi
