#!/usr/bin/env bash
# File: 7-highlander

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM and call handle_sigterm when caught
trap 'handle_sigterm' SIGTERM

# Infinite loop to print message with a sleep interval
while true; do
    echo "To infinity and beyond"
    sleep 2
done
