#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while (( counter < 20 ))
do
echo "$counter"
if (( counter == 3 )); then
 echo "bad luck from China" 
elif ((  counter == 8 )); then
echo "bad luck from Japan" 
elif (( counter == 16 )); then
echo "bad luck from Italy" 
fi
((counter++))
done
