#!/usr/bin/env bash
# This script displaying hours (0,12) and minutes (1,59)
hour=0
minute=1

while (( hour < 12 )) 
do
    echo "Hour: $hour"
    while (( minute < 60 ))
    do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
    minute=1 
done
