#!/usr/bin/env bash
# run Nginx as Nginx
sudo useradd -r -s /sbin/nologin nginx
sudo chown -R /etc/nginx/
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
